version: '3'

networks:
  default:
    external:
      name: local-net

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
      default:
        ipv4_address: 10.128.0.2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  zoo:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks: 
      default:
        ipv4_address: 10.128.0.3
    ports:
      - '2181:2181'

  jupyter:
    image: jupyter/pyspark-notebook
    user: root
    networks:
      default:
        ipv4_address: 10.128.0.7
    ports:
      - 8889:8888