version: '3'

networks:
  default:
    external:
      name: local-net

services:

  hdfs:
    image: hadoop:latest
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      HADOOP_USER: ${HADOOP_USER}
    ports:
      - 50070:50070
      - 8020:8020
      - 50075:50075
      - 50010:50010
      - 50020:50020
      - 8088:8088
      - 8032:8032
    volumes:
      # - ./hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml
      #- ./.bashrc:/root/.bashrc
      - ./entrypoint.sh:/root/entrypoint.sh
      - ./ssh_config:/root/.ssh/config
    networks: 
      default:
        ipv4_address: 10.128.0.14
    environment:
      JAVA_HOME: /usr/local/openjdk-8
      HADOOP_HOME: /usr/local/hadoop
      # PATH: $PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
    working_dir: /usr/local/hadoop/
    command: /bin/bash -c 'chown root:root /root/entrypoint.sh && /root/entrypoint.sh && 
            /usr/local/hadoop/bin/hdfs dfs -mkdir data &&
            /usr/local/hadoop/bin/hdfs dfs -chmod -R 777 data'
